/*
* generated by Xtext
*/
package org.openarchitectureware.vis.blockdiagram.metamodel.ui.contentassist;

import org.openarchitectureware.vis.blockdiagram.metamodel.ui.contentassist.AbstractBlockDiagramProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BlockDiagramProposalProvider extends AbstractBlockDiagramProposalProvider {

}
