/*
 * generated by Xtext
 */
package org.openarchitectureware.vis.blockdiagram.metamodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BlockDiagramUiModule extends org.openarchitectureware.vis.blockdiagram.metamodel.ui.AbstractBlockDiagramUiModule {
	public BlockDiagramUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
