/*
* generated by Xtext
*/
package org.openarchitectureware.vis.contentassist;

import org.openarchitectureware.vis.contentassist.AbstractGraphmm35ProposalProvider;
/**
 * see http://wiki.eclipse.org/Xtext/Documentation#Content_Assist on how to customize content assistant
 */
public class Graphmm35ProposalProvider extends AbstractGraphmm35ProposalProvider {

}
