/*
 * generated by Xtext
 */
package org.openarchitectureware.vis;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphmmRuntimeModule extends org.openarchitectureware.vis.AbstractGraphmmRuntimeModule {

}
