/*
* generated by Xtext
*/
package org.openarchitectureware.vis.graphviz.labeling;

import org.eclipse.xtext.ui.core.DefaultLabelProvider;

/**
 * 
 */
public class DotLabelProvider extends DefaultLabelProvider{
/*
	
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "icons/MyModel.jpg";
    }
	 
*/
}

