/*
* generated by Xtext
*/
package org.openarchitectureware.vis.graphviz.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class DotTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
