/*
 * generated by Xtext
 */
package org.openarchitectureware.vis.graphviz.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://wiki.eclipse.org/Xtext/Documentation#Formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class DotFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
		org.openarchitectureware.vis.graphviz.services.DotGrammarAccess f = (org.openarchitectureware.vis.graphviz.services.DotGrammarAccess) getGrammarAccess();

		//...
	}
}
