
/*
 * generated by Xtext
 */
 
package org.openarchitectureware.vis.graphviz.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class DotExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.openarchitectureware.vis.graphviz.ui.internal.DotActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.openarchitectureware.vis.graphviz.ui.internal.DotActivator.getInstance().getInjector("org.openarchitectureware.vis.graphviz.Dot");
	}
	
}
