/*
* generated by Xtext
*/
package org.openarchitectureware.vis.graphviz.contentassist;

import org.openarchitectureware.vis.graphviz.contentassist.AbstractDotProposalProvider;
/**
 * see http://wiki.eclipse.org/Xtext/Documentation#Content_Assist on how to customize content assistant
 */
public class DotProposalProvider extends AbstractDotProposalProvider {

}
