/*
 * generated by Xtext
 */
package org.xtext.example;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MyDslUiModule extends org.xtext.example.AbstractMyDslUiModule {

}
