/*
* generated by Xtext
*/
package org.openarchitectureware.vis.ui.contentassist;

import org.openarchitectureware.vis.ui.contentassist.AbstractGraphmmProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GraphmmProposalProvider extends AbstractGraphmmProposalProvider {

}
