/*
 * generated by Xtext
 */
package org.openarchitectureware.vis.blockdiagram.metamodel;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BlockDiagramUiModule extends org.openarchitectureware.vis.blockdiagram.metamodel.AbstractBlockDiagramUiModule {

}
