/*
 * generated by Xtext
 */
package org.openarchitectureware.vis.graphviz;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotUiModule extends org.openarchitectureware.vis.graphviz.AbstractDotUiModule {

}
