/*
* generated by Xtext
*/
package org.xtext.example.outline;

import org.eclipse.xtext.ui.common.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class MyDslTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
