/*
 * generated by Xtext
 */
package org.openarchitectureware.vis;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Graphmm35RuntimeModule extends org.openarchitectureware.vis.AbstractGraphmm35RuntimeModule {

}
