/*
* generated by Xtext
*/
package org.openarchitectureware.vis.graphviz.ui.contentassist;

import org.openarchitectureware.vis.graphviz.ui.contentassist.AbstractDotProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DotProposalProvider extends AbstractDotProposalProvider {

}
