/*
 * generated by Xtext
 */
package org.openarchitectureware.vis.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphmmUiModule extends org.openarchitectureware.vis.ui.AbstractGraphmmUiModule {
	public GraphmmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
