/*
* generated by Xtext
*/
package org.openarchitectureware.vis.blockdiagram.metamodel.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class BlockDiagramTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
