/*
* generated by Xtext
*/
package org.openarchitectureware.vis.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class GraphmmTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
