/*
 * generated by Xtext
 */
package org.openarchitectureware.vis.graphviz.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DotUiModule extends org.openarchitectureware.vis.graphviz.ui.AbstractDotUiModule {
	public DotUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
